from django.contrib import admin
from .models import AIProject, Skill


@admin.register(AIProject)
class AIProjectAdmin(admin.ModelAdmin):
    """
    Custom admin interface for AI Projects.
    Makes it easy to add, edit, and manage your projects without touching code.
    """
    
    # Fields to display in the list view
    list_display = ('title', 'category', 'is_published', 'created_at')
    
    # Add filters on the right sidebar
    list_filter = ('category', 'is_published', 'created_at')
    
    # Make title searchable
    search_fields = ('title', 'description', 'summary')
    
    # Group fields into sections in the edit form
    fieldsets = (
        ('Project Info', {
            'fields': ('title', 'summary', 'category', 'description')
        }),
        ('Project Details', {
            'fields': ('business_problem', 'tools_used', 'key_features', 'your_role', 'challenge', 'lessons_learned'),
            'description': 'Fill in the detailed project information'
        }),
        ('Media', {
            'fields': ('image', 'video_url', 'video_file'),
            'description': 'Add a screenshot and/or video to showcase your project (URL or file)'
        }),
        ('Links', {
            'fields': ('deployed_url', 'github_url'),
            'description': 'Add links to your live project and code repository'
        }),
        ('Publishing', {
            'fields': ('is_published',),
        }),
        ('Auto-Generated', {
            'fields': ('slug', 'created_at', 'updated_at'),
            'classes': ('collapse',),  # Hidden by default
        }),
    )
    
    # Make created_at and updated_at read-only
    # (slug is auto-generated by the model, so it's read-only too)
    readonly_fields = ('created_at', 'updated_at', 'slug')


@admin.register(Skill)
class SkillAdmin(admin.ModelAdmin):
    """
    Admin interface for managing skills.
    """
    
    list_display = ('name', 'category', 'proficiency', 'years_experience', 'order')
    list_filter = ('category', 'proficiency')
    search_fields = ('name',)
    ordering = ('category', 'order')
    
    fieldsets = (
        ('Skill Info', {
            'fields': ('name', 'category', 'proficiency')
        }),
        ('Experience', {
            'fields': ('years_experience', 'order')
        }),
    )
