from django.contrib import admin
from .models import AIProject


@admin.register(AIProject)
class AIProjectAdmin(admin.ModelAdmin):
    """
    Custom admin interface for AI Projects.
    Makes it easy to add, edit, and manage your projects without touching code.
    """
    
    # Fields to display in the list view
    list_display = ('title', 'category', 'is_published', 'created_at')
    
    # Add filters on the right sidebar
    list_filter = ('category', 'is_published', 'created_at')
    
    # Make title searchable
    search_fields = ('title', 'description')
    
    # Group fields into sections in the edit form
    fieldsets = (
        ('Project Info', {
            'fields': ('title', 'category', 'description')
        }),
        ('Media', {
            'fields': ('image', 'video_url', 'video_file'),
            'description': 'Add a screenshot and/or video to showcase your project (URL or file)'
        }),
        ('Links', {
            'fields': ('deployed_url', 'github_url'),
            'description': 'Add links to your live project and code repository'
        }),
        ('Publishing', {
            'fields': ('is_published',),
        }),
        ('Auto-Generated', {
            'fields': ('slug', 'created_at', 'updated_at'),
            'classes': ('collapse',),  # Hidden by default
        }),
    )
    
    # Make created_at and updated_at read-only
    # (slug is auto-generated by the model, so it's read-only too)
    readonly_fields = ('created_at', 'updated_at', 'slug')
