# Generated by Django 6.0.4 on 2026-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of your AI project or tool', max_length=200)),
                ('category', models.CharField(choices=[('agents', 'AI Agents'), ('generative_video', 'Generative Video'), ('generative_image', 'Generative Image'), ('django_web_app', 'Django Web App'), ('nlp', 'NLP & Language Models'), ('computer_vision', 'Computer Vision'), ('other', 'Other AI Project')], default='other', help_text='Choose the category that best describes this project', max_length=50)),
                ('description', models.TextField(help_text='Explain what this project does and how you built it (vibe coding style!)')),
                ('image', models.ImageField(blank=True, help_text='Upload a screenshot or hero image for this project', null=True, upload_to='projects/')),
                ('video_url', models.URLField(blank=True, help_text='Paste an embed URL for a video demo (e.g., YouTube embed link)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly name', unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Check to display this project on the gallery')),
            ],
            options={
                'verbose_name': 'AI Project',
                'verbose_name_plural': 'AI Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
