# Generated by Django 6.0.4 on 2026-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproject',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, MOV, etc.) instead of a URL', null=True, upload_to='projects/videos/'),
        ),
    ]
