# Generated by Django 6.0.4 on 2026-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_aiproject_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproject',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to the GitHub repository for this project', null=True),
        ),
    ]
