# Generated by Django 6.0.4 on 2026-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_aiproject_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproject',
            name='deployed_url',
            field=models.URLField(blank=True, help_text='Link to the live deployed version (e.g., Render, Vercel)', null=True),
        ),
    ]
