# Generated by Django 6.0.4 on 2026-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_aiproject_deployed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill or technology', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('ai_ml', 'AI & Machine Learning'), ('databases', 'Databases'), ('tools', 'Tools & Platforms'), ('other', 'Other')], default='tools', help_text='Category this skill belongs to', max_length=50)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Your proficiency level with this skill', max_length=20)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, help_text='Years of experience with this skill', max_digits=3, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order to display skills on the page (0 = default order)')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='aiproject',
            name='business_problem',
            field=models.TextField(blank=True, help_text='What problem does this project solve?'),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='challenge',
            field=models.TextField(blank=True, help_text='What was the biggest challenge you faced?'),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='key_features',
            field=models.TextField(blank=True, help_text='Bullet points or paragraphs describing key features'),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='What did you learn from building this project?'),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='summary',
            field=models.CharField(blank=True, help_text='Quick one-line description of the project', max_length=255),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='tools_used',
            field=models.TextField(blank=True, help_text='List the tools and technologies used (Python, TensorFlow, OpenAI, etc.)'),
        ),
        migrations.AddField(
            model_name='aiproject',
            name='your_role',
            field=models.TextField(blank=True, help_text='What was your specific role and contribution to this project?'),
        ),
    ]
